# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Box/OS
VAGRANT_BOX = 'centos/7'

# Shortcut name
VM_NAME = 'dev-box'

# VM user - 'vagrant' by default
VM_USER = 'vagrant'

# Local username
MAC_USER = 'flung'

# Host folder to sync
HOST_PATH = '/Users/' + MAC_USER + '/dev'

# Where to sync to on Guest - 'vagrant' is the default user name
GUEST_PATH = '/home/' + VM_USER + '/dev'

Vagrant.configure(2) do |config|

  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX

  # Actual machine name
  config.vm.hostname = VM_NAME

  # Set VM nae in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
  end

  config.vm.network "private_network", type: "dhcp"

  # Sync folder
  config.vm.synced_folder HOST_PATH, GUEST_PATH

  # Disable default Vagrant folder, use a unique path per project
  config.vm.synced_folder '.', '/home'+VM_USER+'', disabled: true

end